---
# Ref: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/orgs/42picky/discussions
    about: Any kind of questions should go on the forum.
